-- MySQL Script generated by MySQL Workbench
-- gio 25 nov 2021, 10:53:29
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------


-- -----------------------------------------------------
-- Table `user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(50) NOT NULL,
  `lastname` VARCHAR(50) NOT NULL,
  `username` VARCHAR(60) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` CHAR(100) NOT NULL,
  `telephone` CHAR(10) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `home`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `home` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `user` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_home_user_idx` (`user` ASC),
  CONSTRAINT `fk_home_user`
    FOREIGN KEY (`user`)
    REFERENCES `user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `room` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `home` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_room_home1_idx` (`home` ASC),
  CONSTRAINT `fk_room_home1`
    FOREIGN KEY (`home`)
    REFERENCES `home` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `device`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `device` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `room` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_device_room1_idx` (`room` ASC),
  CONSTRAINT `fk_device_room1`
    FOREIGN KEY (`room`)
    REFERENCES `room` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `device_light`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `device_light` (
  `device` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `status` ENUM('on', 'off') NOT NULL,
  PRIMARY KEY (`device`),
  CONSTRAINT `fk_device_light_device1`
    FOREIGN KEY (`device`)
    REFERENCES `device` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `device_window`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `device_window` (
  `device` INT UNSIGNED NOT NULL,
  `status` ENUM('open', 'close') NOT NULL,
  PRIMARY KEY (`device`, `status`),
  CONSTRAINT `fk_table1_device1`
    FOREIGN KEY (`device`)
    REFERENCES `device` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `device_thermostat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `device_thermostat` (
  `device` INT UNSIGNED NOT NULL,
  `temperature` INT NOT NULL,
  `umidity` ENUM('heat', 'cool', 'dry', 'fan') NOT NULL,
  PRIMARY KEY (`device`),
  CONSTRAINT `fk_device_thermostat_device1`
    FOREIGN KEY (`device`)
    REFERENCES `device` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `device_alarm`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `device_alarm` (
  `device` INT UNSIGNED NOT NULL,
  `status` ENUM('on', 'off') NOT NULL,
  PRIMARY KEY (`device`),
  CONSTRAINT `fk_device_alarm_device1`
    FOREIGN KEY (`device`)
    REFERENCES `device` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
